/// <reference path="datepickerNew/bootstrap.datepickerNew.d.ts" />
/// <reference path="jquery/jquery.d.ts" />
/// <reference path="angular/angular.d.ts" />
/// <reference path="toastr/toastr.d.ts" />
/// <reference path="underscore/underscore.d.ts" />
/// <reference path="moment/moment.d.ts" />
/// <reference path="rickshaw/rickshaw.d.ts" />
/// <reference path="bootbox/bootbox.d.ts" />
/// <reference path="highcharts/highcharts.d.ts" />
//# sourceMappingURL=reference.js.map
